<a href="https://colab.research.google.com/github/surendra-crax/120Days-DataScience/blob/main/Day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What NumPy Actually Is

- NumPy = “Numerical Python”

It gives you:

- Fast arrays (better than Python lists)

- Vectorized math (entire array operations without loops)

- Matrix operations (critical for ML)

- Highly optimized performance (C-level speed)

- Everything in Data Science starts with NumPy arrays.

In [2]:
#creating arrays
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
#creating 2D arrays
mat = np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [12]:
#auto generated arrays
import numpy as arr
arr1 = arr.arange(10)     # 0 to 9
arr2 = arr.zeros((3,3))   # 3x3 matrix of 0's
arr3 = arr.ones((2,4))   # 2x4 matrix of 1's
arr4 = arr.linspace(0,1,5)     #5 values from 00 to 1
print(arr1)
print(arr2)
print(arr3)
print(arr4)


[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.   0.25 0.5  0.75 1.  ]


In [14]:
# array properties
print(arr1.ndim)        #dimensions (1d,2d,3,d....)
print(arr1.shape)       #rows,columns
print(arr1.size)        #total elemtns
print(arr1.dtype)       #data type

1
(10,)
10
int64


In [38]:
#indexing and slicing
array1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#print(array1)
#1d indexing
print(array1[0])
print(array1[1])
print(array1[0][0])
print(array1[0][1])
print(array1[0][2])
print(array1[0][3])
#1d slicing
print(array1[1:4])
print(array1[:3])
#2d indexing
print(array1[0,1])
print(array1[1,:])  #entire row 1
print(array1[:,2]) #entire column
print(array1[2,:]) #entire row 2

[1 2 3 4]
[5 6 7 8]
1
2
3
4
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[5 6 7 8]
[ 3  7 11]
[ 9 10 11 12]


In [41]:
#reshaping
arr = np.arange(12)
print(arr.reshape(3,4))
print(arr.reshape(2,6))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [44]:
#vectorized operations
arr =np.array([1,2,3])

print(arr + 5)
print(arr * 5)
print(arr ** 5)
print(arr + arr)

[6 7 8]
[ 5 10 15]
[  1  32 243]
[2 4 6]


In [46]:
#broadcasting
mat1 = np.array([[1,2,3],[4,5,6]])

mat+10                          #adds 10 to every element

array([[11, 12, 13],
       [14, 15, 16]])

| Function    | Output Type | Range               | Shape         |
| ----------- | ----------- | ------------------- | ------------- |
| `randint()` | integers    | [low, high)         | given by size |
| `rand()`    | floats      | [0, 1)              | given by args |
| `randn()`   | floats      | normal distribution | given by args |


In [50]:
#random module
print(np.random.randint(1,100,size=(3,3)))
print(np.random.rand(3,4))
print(np.random.randn(2,2))

[[24  2 65]
 [40 45 64]
 [46 73 92]]
[[0.10671245 0.6345255  0.21429374 0.4609906 ]
 [0.02405583 0.87433658 0.27874672 0.90179599]
 [0.53564766 0.10224951 0.98108839 0.03472121]]
[[-1.24373508  0.51054476]
 [ 0.30244307 -1.19726749]]


In [51]:
#matrix operations
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

A @ B         #matrix multiplication
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [53]:
#statistics
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.std())
print(arr.sum())

1
3
2.0
0.816496580927726
6


#Advanced practice

In [54]:
arr = np.arange(20)
print(arr[2:15:3])         #start:top:step

[ 2  5  8 11 14]


In [55]:
arr = np.arange(30)
print(arr[5:25:2])

[ 5  7  9 11 13 15 17 19 21 23]


In [56]:
#boolean masking
arr = np.array([5,12,18,7,30])

mask = arr>10
print(mask)
print(arr[mask])

[False  True  True False  True]
[12 18 30]


In [59]:
#practice question
arr = np.arange(20)

mask = (arr%2==0)
print(mask)
print(arr[mask])

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
[ 0  2  4  6  8 10 12 14 16 18]


In [58]:
#multiple conditions
arr[(arr>10) &  (arr<25)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
#practice question
arr[(arr>5) & (arr<50) & (arr%2==0)]

array([ 6,  8, 10, 12, 14, 16, 18])

In [62]:
#fancy indexing
arr = np.array([10,20,30,40,50])
print(arr[[0,3,4]])

[10 40 50]


In [64]:
#practice
arr =np.array([1,4,5,6,78,899,6,5,5,34,3,4,5,56,])
print(arr[[2,5,7,9]])

[  5 899   5  34]


In [69]:
#axis operations
mat = np.array([[1,2,3],[4,5,6]])
print(mat.sum(axis=0))       #column-wise sum
print(mat.sum(axis=1))       #row wise sum

[5 7 9]
[ 6 15]


In [71]:
#practice
mat1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(mat1.sum(axis=0))
print(mat1.sum(axis=1))

[15 18 21 24]
[10 26 42]


In [73]:
#stacking arrays
a = np.array([12,3,45])
b = np.array([23,32,15])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[12  3 45]
 [23 32 15]]
[12  3 45 23 32 15]


In [77]:
#spliting arrays
arr = np.arange(10)
print(np.split(arr,2))
arr1 = np.arange(12)
print(np.split(arr1,3))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


In [80]:
#copy vs view
a = np.array([1,2,3])
b = a.copy()
b[0] = 99
print(a)

[1 2 3]


In [81]:
#broadcasting
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(mat + np.array([10,20,30]))

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [83]:
#1. Create a 1D array of 30 numbers from 10 to 39.
arr = np.arange(10,40)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


In [87]:
#2. Create a 4×5 matrix filled with the number 7.
import numpy as arr
arr1 = arr.full((4,5),7)
print(arr1)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [88]:
#3. Create a 3×3 identity matrix.
arr2 = arr.eye(3)
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [96]:
#4. From a 10-element array, print:
#first 4 values
#last 4 values
#middle 2 values

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr[0:4])
print(arr[-4:])
print(arr[len(arr)//2-1:arr[len(arr)//2]])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4]
[ 7  8  9 10]
[5 6]


In [98]:
#5. From a 4×4 matrix, extract the diagonal elements.
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(np.diag(array))

[ 1  6 11 16]


In [99]:
#6.given an array ,return all values>50
import numpy as np

arr = np.array([10,55,32,78,99,12])
print(arr[arr > 50])


[55 78 99]


In [100]:
#7. Filter all even numbers from a random array
arr = np.random.randint(1, 100, size=15)
print(arr[arr % 2 == 0])


[76 86 92 14 18 88 54]


In [101]:
#8. Filter values between 20 and 40 (inclusive)
arr = np.array([5,21,35,40,41,18,33])
print(arr[(arr >= 20) & (arr <= 40)])


[21 35 40 33]


In [102]:
#9. Extract elements at indices [1,3,5] from [10,20,30,40,50,60]
arr = np.array([10,20,30,40,50,60])
result = arr[[1,3,5]]
print(result)


[20 40 60]


In [103]:
#10. Column-wise mean of a 3×4 matrix
mat = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(mat.mean(axis=0))


[5. 6. 7. 8.]


In [104]:
#11. Row-wise max of a 5×5 random matrix
mat = np.random.randint(1, 100, size=(5,5))
print(mat)
print("Row-wise max:", mat.max(axis=1))


[[73 43 88 46 95]
 [86 99 23 72 45]
 [14 18 23 80 14]
 [27 33  8 69 91]
 [96 14 80 29 55]]
Row-wise max: [95 99 80 91 96]


In [105]:
#12. Vertically stack two 1D arrays
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a, b)))


[[1 2 3]
 [4 5 6]]


In [106]:
#14. Split a 12-element array into 3 equal parts
arr = np.arange(12)
parts = np.split(arr, 3)
print(parts)


[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


In [107]:
#15. Convert 1D array of 15 numbers → 3×5 matrix
arr = np.arange(15)
mat = arr.reshape(3, 5)
print(mat)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [108]:
#16. Convert 2×6 matrix → 3×4 matrix
mat = np.arange(12).reshape(2,6)
new_mat = mat.reshape(3,4)
print(new_mat)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [109]:
#17. Add [5,10,15] to a 3×3 matrix
mat = np.arange(9).reshape(3,3)
v = np.array([5,10,15])

print(mat + v)


[[ 5 11 17]
 [ 8 14 20]
 [11 17 23]]


In [111]:
#18. Subtract [1,2,3,4] from every row of a 4×4 matrix
mat = np.arange(16).reshape(4,4)
v = np.array([1,2,3,4])

print(mat - v)



[[-1 -1 -1 -1]
 [ 3  3  3  3]
 [ 7  7  7  7]
 [11 11 11 11]]


In [112]:
#19. Show that modifying .view() affects original array
a = np.array([1,2,3])
b = a.view()
b[0] = 99

print("Original:", a)
print("View:", b)


Original: [99  2  3]
View: [99  2  3]


In [113]:
#20. Show that modifying .copy() does NOT affect original
a = np.array([1,2,3])
b = a.copy()
b[0] = 99

print("Original:", a)
print("Copy:", b)


Original: [1 2 3]
Copy: [99  2  3]
