<a href="https://colab.research.google.com/github/surendra-crax/120Days-DataScience/blob/main/Mock_Test_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. What is the difference between a list and a tuple?

List is mutable and tuple is immutable
List has so many operations using built in methods.And to make changes in tuple we have to do type casting and change it to list and apply operatiosna nd again cast into tuple.

# 2. Predict the output:



```
x = [1, 2, 3]
y = x
y.append(4)
print(x)
```
Answer:
[1,2,3,4]


# 3. Rewrite the code using f-strings:

print("Name:" + name + " Age:" + str(age))

output:
print(f"Name:{name}+Age:{str(age)})

# 4. What does slicing [::-1] do?

Print the outpur in reverse


# 5. What will this print?


```

for i in range(3):
    print(i,end=" ")
```
Answer: 1 2


# 6. Write logic (not code) to check if a number is prime.

Answer:
->take input n
->start for loop from 2,n:
->if n%i==0:
->print the number is not prime
->else: print the number is prime

# 8. Predict the output:



```
total = 0
for i in range(1,6):
    total += i
print(total)
```
Answer:
it prints sum of 1,2,3,4,5 and answer is 15



# 9. Write the logic to reverse a string without slicing.

Answer:
n = "Hello"
m = ""
for i in range(len(n)-1,-1,-1):
  m = m+n[i]
print(m)

# 10. Predict the output:


```
i = 5
while i > 0:
    i -= 1
    print(i, end=" ")

```

Answer:
4,3,2,1

# 11. What is the difference between return and print?
Answer:
return keyword prints a value like integer value
print keyqord prints output to the screen.

# 12. Write the logic for a function that counts vowels in a string.

Answer:

->take string input

->create a list of all vowels

->start a loop compare every character from string to list and
increase copunt variable value

->Orint the output of count

#13. What is *args used for? Give one example.

Answer:

So the "*args" is used when we dont how many arguments we pass through functions


```
def my_func(*args):
  print(sum(*args))

my_func(1,2,3,4)
```



In [ ]:
def my_func(*args):
  print(*args)

my_func(1,2,3,4)


1 2 3 4


# 14. What is recursion? Explain in one line.
Answer:
Recursion is a repetetive code block that uses to solve problems where the same logic need to be applied.It makes the run time very less and optimize the storage.

# 15. Why should you avoid writing infinite recursion?

Answer:
We should not write infinite recursion our memory will be exhausted annd GPU process will be decreased.Our resources will be exhausted.

# 16. Write the steps to read a file line by line.

Answer:

->we have to open a file first

->and then we need to use readline() method

->The content of file comes line by line

# 17. What exception occurs when dividing by zero?

Answer:

Zero division error

# 18. What does this code print?



```
try:
    x = 10/0
except:
    print("error")

```

Answer:

error


# 19. Explain the purpose of finally block.

Answer:
This is a section which print after try and catch if both doesnt process correctly.It means it is used to perform some thing aftr exception occured or no exception occured also.

# 20. When should you use a custom exception?

Answer:

We should use custom exception is the error that comes is not a default exception type avilable in python or if we want to print some custom output for a exception.

#21. What is the difference between a NumPy array and a Python list?

Answer:

The lists are used to store multiple values and also it supports different datatypes.Same numpy also stores multiple values but of same data type.

# 22. Create a 1D NumPy array containing numbers 1 to 10.

Answer:



```
import numpy as np

a= np.array([1,2,3,4,5,6,7,8,10])
print(a)
```



In [ ]:
import numpy as np

a= np.array([1,2,3,4,5,6,7,8,10])
print(a)

[ 1  2  3  4  5  6  7  8 10]


# 23. What does reshape(3,4) do?

Answers:
It converts the size of array means it converts the array into size of 3rows*4columns

# 24. Explain broadcasting with a simple example.

Answer:
Broadcasting is making it emphasize means increases it according to uses like applying some operations on them.
for example:


```
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,10])
print(a*2)
```



In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,10])
print(a*2)

[ 2  4  6  8 10 12 14 16 20]


# 25. What does this print?



```
import numpy as np
a = np.array([1,2,3])
b = np.array([10,10,10])
print(a + b)

```
Answer:
[11,12,13]


#26. What does df.head() show?

Answer:

df.head() is amethod used in panda when working with tables.So it print first 5 rows of the table.

#27. What is the difference between loc and iloc?

Answers:

loc: used to retrieve table data using column names.
iloc: used to retrieve dataa using indexing i stands for index.

# 28. Select only the "Age" column from Titanic dataset.


Answer:



```
from google.colab import files
upload = files.upload()

import pandas as pd
df = pd.read_csv("titanic.csv")
c = print(df["Age"])
print(c)

```



In [ ]:
from google.colab import files
upload = files.upload()

Saving titanic.csv to titanic (1).csv


In [ ]:
import pandas as pd
df = pd.read_csv("titanic.csv")
c = print(df["Age"])
print(c)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64
None


# 29. Write a filter that selects passengers older than 50.


Answer:
```
c = print(df[df["Age"]>50])
print(c)
```



In [ ]:
c = print(df[df["Age"]>50])
print(c)

     PassengerId  Survived  Pclass  \
6              7         0       1   
11            12         1       1   
15            16         1       2   
33            34         0       2   
54            55         0       1   
..           ...       ...     ...   
820          821         1       1   
829          830         1       1   
851          852         0       3   
857          858         1       1   
879          880         1       1   

                                                  Name     Sex   Age  SibSp  \
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
33                               Wheadon, Mr. Edward H    male  66.0      0   
54                      Ostby, Mr. Engelhart Cornelius    male  65.0      0   
..                                                 ...     ...   ... 

# 30. What does df.isnull().sum() do?

Answer:

It returens the sum of rows which have null values.

# 31. Group Titanic by Sex and get mean Age.

Answer:



```
print(df.groupby("Sex")["Age"].mean())
```



In [ ]:
print(df.groupby("Sex")["Age"].mean())

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64


#32. What does value_counts() return?

Answer:

value_counts returns the value of count of unique values in series.

# 33. Explain inner vs left vs outer join in one line each.

Answer:
inner join: It combines two tables with having same values of same column which present in both table
Left join: It combines two tables with keeping the value from left  table number.

# 34. What does this pivot table show?



```
df.pivot_table(index="Sex", columns="Pclass", values="Survived")

```
Answer:

Yeah this returns the values in table format as rows as "Male and female and columns as Pclass as 1,2,3 and value of table according to sex and pclass.


# 35. Write the merge logic conceptually:
Combine dfA (Name, ID) with dfB (Marks, ID) into one table.

Answer:



```
pd.merge(dfA,dbB,on="ID",how="inner")
```



# 36. Write a function that removes duplicates from a list.

Answer:

We can use two ways:

One:

We can take empty list and a loop to compare values and add values to empty list if it comes two time.....only one time adding to list.

Two:

Another way is convert list to set and again convert set to list.We know set will have uniwue values....so that works.

#37. Write a NumPy program to generate a 3×3 matrix of random integers.

Answer:



```
arr = np.random.randint(0,100,size=(3,3))
```



In [ ]:
arr = np.random.randint(0,100,size=(3,3))
print(arr)

[[79 96 23]
 [88 57 16]
 [83 59 74]]


#38. Write a Pandas filter to select all female survivors.

Answers:



```
df[(df["Sex"] == "female") & (df["Survived"] == 1)]

```



In [ ]:
df[(df["Sex"] == "female") & (df["Survived"] == 1)]


PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
874          875         1       2   
875          876         1       3   
879          880         1       1   
880          881         1       2   
887          888         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1   
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
874      0         P/PP 3381  24.0000   NaN        C  
875      0              2667   7.2250   NaN        C  
879      1             11767  83.1583   C50        C  
880      1            230433  26.0000   NaN        S  
887      0            112053  30.0000   B42        S  

[233 rows x 12 columns]

# 39. Write a Pandas command to sort Titanic by Fare descending.

Answer:



```
print(df.sort_values(by="Fare", ascending = False))
```



In [ ]:
print(df.sort_values(by="Fare", ascending = False))

     PassengerId  Survived  Pclass                                Name  \
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
258          259         1       1                    Ward, Miss. Anna   
737          738         1       1              Lesurer, Mr. Gustave J   
88            89         1       1          Fortune, Miss. Mabel Helen   
438          439         0       1                   Fortune, Mr. Mark   
..           ...       ...     ...                                 ...   
806          807         0       1              Andrews, Mr. Thomas Jr   
815          816         0       1                    Fry, Mr. Richard   
466          467         0       2               Campbell, Mr. William   
481          482         0       2    Frost, Mr. Anthony Wood "Archie"   
822          823         0       1     Reuchlin, Jonkheer. John George   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
679    male  36.0      0      1  PC

# 40. Write a pivot table to show average Fare per Class.

Answer:



```
print(df.pivot_table(index="Pclass", values="Fare",aggfunc="mean"))
```



In [ ]:
print(df.pivot_table(index="Pclass", values="Fare",aggfunc="mean"))

             Fare
Pclass           
1       84.154687
2       20.662183
3       13.675550
